version: "3.3"
services:
  # nginx
  nginx:
    build: nginx/
    ports:
      - "80:80"
    links:
      - web1:app_1
      - web2:app_2
      - web3:app_3
      - web4:app_4
  mongodb:
    image: bitnami/mongodb:latest
    ports: [
      "27017:27017"
    ]
    volumes:
      - /data/db:/data/db
    environment:
      - MONGODB_USER=felipe19rodrigues64
      - MONGODB_PASSWORD=folR272812
      - MONGODB_DATABASE=app_db
      - MONGODB_ROOT_PASSWORD=folR272812
  web1:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongodb  
      #ports: ["3000:3000"]
  web2:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongodb
      #ports: ["3000:3000"]
  web3:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongodb
      #ports: ["3000:3000"]
  web4:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mongodb
      #ports: ["3000:3000"]

